In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Infosys_Dataset.xlsx to Infosys_Dataset.xlsx

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('Infosys_Dataset.xlsx')

In [ ]:
df.shape

(2599, 24)

In [ ]:
df.head()

,Order ID,Type,Days for shipping (real),Days for shipment (scheduled),Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Segment,Department Name,...,Sales,Unit Price,Order Item Total,Order Profit Per Order,Order Region,Order Status,Product Name,shipping date,Shipping Mode,Inventory Stock (Units)
0,ORD100001,CASH,3.0,1.0,Late delivery,1.0,Books,Dallas,Home Office,Sports,...,3521.07,704.214000,3504.60,104.58,Central,CLOSED,Keyboard,05/07/2023,Second Class,2885.0
1,ORD100002,DEBIT,6.0,6.0,Advance shipping,0.0,Electronics,Phoenix,Corporate,Fashion,...,1506.54,502.180000,1483.86,218.45,South,CLOSED,Desk,01/30/2023,Standard Class,5232.0
2,ORD100003,CASH,6.0,6.0,Advance shipping,0.0,Sports,Los Angeles,Corporate,Fashion,...,890.72,148.453333,889.25,-17.61,South,SUSPECTED_FRAUD,Keyboard,10/14/2023,Second Class,2885.0
3,ORD100004,CASH,8.0,6.0,Late delivery,1.0,Office Supplies,Dallas,Consumer,Technology,...,1267.53,181.075714,1226.66,18.87,South,CLOSED,Printer,02/01/2024,Standard Class,4373.0
4,ORD100005,PAYMENT,2.0,1.0,Late delivery,1.0,Furniture,Houston,Corporate,Home,...,3662.80,457.850000,3629.32,-7.60,North,PENDING,Keyboard,12/19/2023,First Class,2885.0

In [ ]:
df.tail()

,Order ID,Type,Days for shipping (real),Days for shipment (scheduled),Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Segment,Department Name,...,Sales,Unit Price,Order Item Total,Order Profit Per Order,Order Region,Order Status,Product Name,shipping date,Shipping Mode,Inventory Stock (Units)
2594,ORD102595,PAYMENT,3.0,3.0,Advance shipping,0.0,Health,Denver,Corporate,Books,...,671.65,671.650000,642.60,22.88,South,PENDING,Keyboard,09/03/2023,First Class,2885.0
2595,ORD102596,CASH,1.0,2.0,Shipping on time,0.0,Office Supplies,Denver,Corporate,Furniture,...,2280.34,760.113333,2247.61,158.83,West,SUSPECTED_FRAUD,Headphones,07/01/2024,Same Day,4720.0
2596,ORD102597,PAYMENT,6.0,4.0,Late delivery,1.0,Health,Denver,Corporate,Office,...,5564.15,618.238889,5546.67,77.01,North,COMPLETE,Backpack,01/26/2025,First Class,4567.0
2597,ORD102598,DEBIT,1.0,1.0,Advance shipping,0.0,Home,Boston,Consumer,Fashion,...,3802.75,633.791667,3769.84,82.41,Central,PENDING,Office Chair,10/11/2024,Standard Class,4256.0
2598,ORD102599,DEBIT,3.0,3.0,Shipping on time,0.0,Health,Miami,Home Office,Furniture,...,368.11,92.027500,359.48,194.18,Central,CLOSED,Office Chair,11/19/2024,Same Day,4256.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2599 entries, 0 to 2598
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Order ID                       2599 non-null   object
 1   Type                           2593 non-null   object
 2   Days for shipping (real)       2593 non-null   float64
 3   Days for shipment (scheduled)  2587 non-null   float64
 4   Delivery Status                2592 non-null   object
 5   Late_delivery_risk             2590 non-null   float64
 6   Category Name                  2588 non-null   object
 7   Customer City                  2589 non-null   object
 8   Customer Segment               2590 non-null   object
 9   Department Name                2584 non-null   object
 10  Market                         2592 non-null   object
 11  Order Country                  2592 non-null   object
 12  order date                     2599 non-null   object
 13  Order Item Quantity            2599 non-null   int64
 14  Sales                          2599 non-null   float64
 15  Unit Price                     2599 non-null   float64
 16  Order Item Total               2589 non-null   float64
 17  Order Profit Per Order         2592 non-null   float64
 18  Order Region                   2587 non-null   object
 19  Order Status                   2596 non-null   object
 20  Product Name                   2593 non-null   object
 21  shipping date                  2599 non-null   object
 22  Shipping Mode                  2596 non-null   object
 23  Inventory Stock (Units)        2593 non-null   float64
dtypes: float64(8), int64(1), object(15)
memory usage: 487.4+ KB

In [ ]:
df.isnull().sum()

Order ID                          0
Type                              6
Days for shipping (real)          6
Days for shipment (scheduled)    12
Delivery Status                   7
Late_delivery_risk                9
Category Name                    11
Customer City                    10
Customer Segment                  9
Department Name                  15
Market                            7
Order Country                     7
order date                        0
Order Item Quantity               0
Sales                             0
Unit Price                        0
Order Item Total                 10
Order Profit Per Order            7
Order Region                     12
Order Status                      3
Product Name                      6
shipping date                     0
Shipping Mode                     3
Inventory Stock (Units)           6
dtype: int64

In [ ]:
df['Order Item Total'] = df['Order Item Quantity'].fillna(df['Order Item Total'].median())

In [ ]:
df.columns

Index(['Order ID', 'Type', 'Days for shipping (real)',
       'Days for shipment (scheduled)', 'Delivery Status',
       'Late_delivery_risk', 'Category Name', 'Customer City',
       'Customer Segment', 'Department Name', 'Market', 'Order Country',
       'order date ', 'Order Item Quantity', 'Sales', 'Unit Price',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order Status', 'Product Name', 'shipping date', 'Shipping Mode',
       'Inventory Stock (Units)'],
      dtype='object')

In [ ]:
df.rename(columns=
 {
     'Late_delivery_risk': 'Late Delivery Risk',
     'order date ': 'Order Date',
     'shipping date': 'Shipping Date'
 }, inplace=True)

In [ ]:
df.columns

Index(['Order ID', 'Type', 'Days for shipping (real)',
       'Days for shipment (scheduled)', 'Delivery Status',
       'Late Delivery Risk', 'Category Name', 'Customer City',
       'Customer Segment', 'Department Name', 'Market', 'Order Country',
       'Order Date', 'Order Item Quantity', 'Sales', 'Unit Price',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order Status', 'Product Name', 'Shipping Date', 'Shipping Mode',
       'Inventory Stock (Units)'],
      dtype='object')

In [ ]:
category_columns = [
    'Type',
    'Delivery Status',
    'Category Name',
    'Customer City',
    'Customer Segment',
    'Department Name',
    'Market',
    'Order Country',
    'Order Region',
    'Order Status',
    'Product Name',
    'Shipping Mode',
]
df[category_columns] = df[category_columns].fillna(df[category_columns].mode().iloc[0])

In [ ]:
numerical_cols = [
    'Days for shipping (real)',
    'Days for shipment (scheduled)',
    'Late Delivery Risk',
    'Order Profit Per Order',
    'Inventory Stock (Units)'
]
df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].mean())

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Order ID                         0
Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Delivery Status                  0
Late Delivery Risk               0
Category Name                    0
Customer City                    0
Customer Segment                 0
Department Name                  0
Market                           0
Order Country                    0
Order Date                       0
Order Item Quantity              0
Sales                            0
Unit Price                       0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order Status                     0
Product Name                     0
Shipping Date                    0
Shipping Mode                    0
Inventory Stock (Units)          0
dtype: int64

In [ ]:
Total_sales = df['Sales'].sum()
print("Total_sales:", Total_sales)

Total_sales: 6130170.28

In [ ]:
Total_Orders = df['Order ID'].count()
print("Total_Orders:", Total_Orders)

Total_Orders: 2599

In [ ]:
Avg_delivery_days = df['Days for shipping (real)'].mean()
print("Avg_delivery_days:", round(Avg_delivery_days,2))

Avg_delivery_days: 3.95

In [ ]:
On_time_orders = (df["Delivery Status"] == "Shipping on time").sum()
Total_Orders = df['Order ID'].count()
On_time_percentage = (On_time_orders/Total_Orders)*100
print("On_time_percentage :", round(On_time_percentage,2), "%")

On_time_percentage : 32.13 %

In [ ]:
df.to_excel("cleaned_data.xlsx", index=False)

In [ ]:
import os

print(os.path.exists("cleaned_data.xlsx"))

True

In [ ]:

files.download("cleaned_data.xlsx")